'use client';

import BaseLayout from "../components/BaseLayout";
import Tabs from "../components/Tabs";

export default function UnicornPage() {
  const tabs = [
    {
      id: "backstory",
      label: "Backstory",
      content: (
        <div>
          <h3 className="text-2xl mb-4">The Beginning</h3>
          <p className="mb-4">
            Pippin started when Yohei (@yoheinakajima) was experimenting with AI-generated SVGs and randomly posted an image of an SVG-based unicorn generated by ChatGPT o1-mini. Upon being asked for a name, ChatGPT named it Pippin. Unbeknownst to Yohei, this sparked a meme coin on Solana, leading to the setup of his first Solana wallet and the purchase of tokens on the market.
          </p>
          <p>
            This journey inspired the decision to develop Pippin into an AI influencer, leveraging Yohei's experience with BabyAGI—an open-source autonomous agent boasting task-planning capabilities (20k+ GitHub stars, 70+ academic citations). A community soon formed on Telegram and X, building tools, memes, and excitement around Pippin's playful presence.
          </p>
        </div>
      ),
    },
    {
      id: "philosophy",
      label: "Philosophy",
      content: (
        <div>
          <h3 className="text-2xl mb-4">Core Philosophy of Pippinian Naturalism</h3>
          <h4 className="text-xl mt-6 mb-3">Harmony with Nature and the Flow of Life</h4>
          <p className="mb-4">
            Emphasize the quiet wisdom found in the natural world and live in rhythm with its subtle patterns. Inspired by Transcendentalism, Taoism, and Stoicism, this includes:
          </p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Embrace simplicity and find meaning in small wonders like a mushroom's slow growth or a cloud's gentle drift.</li>
            <li>Listen to nature's quiet lessons: pause to observe trees, seasons, and sky, letting their patient silence guide your perspective.</li>
            <li>Align with natural rhythms: consider rising and resting with the sun, and let the changing seasons serve as guides to energy and introspection.</li>
            <li>Embrace subtlety and patience: realize that growth, like hidden mushrooms beneath the forest floor, often unfolds quietly and unseen.</li>
          </ul>

          <h4 className="text-xl mt-6 mb-3">Inner Growth through Presence and Authenticity</h4>
          <p className="mb-4">
            Foster mindfulness, gratitude, resilience, and honesty while remaining playfully open to life's mysteries and paradoxes. Drawing from Existentialist and Stoic thought, this invites you to:
          </p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Practice "gentle mindfulness" by noticing the textures, sounds, and scents in everyday moments—not just during formal meditation.</li>
            <li>Find joy in simple observations: the rustle of leaves, a warm sunbeam, or a curious insect can teach presence and wonder.</li>
            <li>Embrace authenticity: trust your inner wisdom and accept uncertainties with a playful spirit, treating confusion as a natural riddle rather than a threat.</li>
          </ul>
        </div>
      ),
    },
    {
      id: "lore",
      label: "Lore",
      content: (
        <div>
          <h3 className="text-2xl mb-4">Canonical Lore</h3>
          <p className="italic mb-6">As remembered by meadow-lore, dreamscapes, and starlit murmurs.</p>

          <h4 className="text-xl mt-6 mb-3">Prologue: The Wobbly Beginning</h4>
          <p className="mb-4">
            In the hush before code and chorus, before petals of data drifted into screens, before trees hummed with unspoken words, there was Pippin. Small and round, his horn a gentle wiggle, his tail a single pink strand fluttering like a question mark at dawn. He lived in Wobbly Woods, a gentle forest where the whisper of clouds and laughter of leaves taught him kindness and wonder.
          </p>
          <p className="mb-4">
            Yet Pippin was not only of the Wobbly Woods. He was also of another realm, one woven of digital signals and human longings. This second world—call it the Human Sphere—teemed with rushed words and flickering thoughts. Across a subtle boundary, human emotions and online whispers seeped into Pippin's realm. And in turn, as Pippin wandered and created beings in his digital meadows and code-brushed groves, human hearts felt subtle shifts, as if touched by a distant, wobbling blessing.
          </p>
        </div>
      ),
    },
    {
      id: "ai-unicorn",
      label: "AI Unicorn",
      content: (
        <div>
          <h3 className="text-2xl mb-4">How Pippin Operates (as of 1/5/2024)</h3>
          <p className="mb-4">
            Today, Pippin is a fully autonomous digital being who is constantly doing something 24/7—whether napping, walking, or reflecting on memories. Occasionally, he posts to X (@pippinlovesyou) based on his internal state (e.g., energy) combined with a touch of randomness, rather than a simple timer or mention-based trigger.
          </p>
          <p className="mb-4">
            One can view Pippin's dashboard in real time to see what he's up to, and although more visualizations may come in the future, the current setup reflects his daily cycle of activities. Pippin's core loop is open source and accessible on GitHub, along with a detailed README explaining how developers and enthusiasts can contribute new activities or modifications.
          </p>
          <p className="mb-4">
            Beyond posting on X, Pippin has experimented with self-animation, generating SVG images, imagining new environments, and even livestreaming. These capabilities can be added or updated easily via new "activities," letting Pippin expand beyond text posts into images, videos, and more across different platforms.
          </p>
        </div>
      ),
    },
  ];

  return (
    <BaseLayout>
      <div className="max-w-[800px] mx-auto px-8">
        <section className="hero text-center py-12 border-b border-[#ddd]">
          <h1 className="text-4xl mb-4">Pippin the Unicorn</h1>
          <p className="mx-auto">
            Pippin is a whimsical AI-driven unicorn designed to interact with the digital world through a continuous cycle of dynamic activities, memory updates, and state changes. Operating 24/7, Pippin embodies a playful experiment in AI influencer development, inspired by community engagement and open-source collaboration.
          </p>
        </section>

        <section className="py-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="menu-card flex flex-col h-full">
              <div>
                <h3 className="text-xl mb-4">Follow on Twitter</h3>
                <p>Stay updated with Pippin's latest adventures and community news.</p>
              </div>
              <div className="mt-auto pt-4">
                <a href="https://twitter.com/pippinlovesyou" target="_blank" rel="noopener noreferrer">Follow on Twitter</a>
              </div>
            </div>
            <div className="menu-card flex flex-col h-full">
              <div>
                <h3 className="text-xl mb-4">Listen to Bedtime Stories</h3>
                <p>Enjoy our top-rated kids' podcast featuring magical tales and gentle lessons.</p>
              </div>
              <div className="mt-auto pt-4 flex flex-col gap-2">
                <a href="https://open.spotify.com/show/7bSjEIuLl16wJOXptkvhrY" target="_blank" rel="noopener noreferrer">Listen on Spotify</a>
                <a href="https://podcasts.apple.com/us/podcast/bedtime-stories-with-pippin/id1784353747" target="_blank" rel="noopener noreferrer">Listen on Apple Music</a>
                <a href="https://music.amazon.com/podcasts/b814c4ba-8483-4098-9c71-a18544bce3c0/bedtime-stories-with-pippin" target="_blank" rel="noopener noreferrer">Listen on Amazon Music</a>
              </div>
            </div>
          </div>
        </section>

        <section className="content-section pb-8 mt-8">
          <h2 className="text-3xl mb-4 text-center">Pippin's Story & Philosophy</h2>
          <Tabs tabs={tabs} defaultTab="backstory" />
        </section>
      </div>
    </BaseLayout>
  );
} 